# Generated by Django 6.0.3 on 2026-09-14 08:35

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='Afro Cure — Maison de soins', max_length=200)),
                ('hero_title_line1', models.CharField(default="L'élégance", max_length=200)),
                ('hero_title_emphasis', models.CharField(default='naturelle', max_length=200)),
                ('hero_title_line2', models.CharField(default='des cheveux', max_length=200)),
                ('hero_subtitle', models.TextField(default='Des soins luxueux pour cheveux texturés. Combinant science cosmétique et plantes africaines.')),
                ('hero_cta_primary_label', models.CharField(default='Découvrir nos soins', max_length=100)),
                ('hero_cta_secondary_label', models.CharField(default='Notre histoire', max_length=100)),
                ('hero_stats', models.JSONField(default=content.models.default_hero_stats)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('marquee_items', models.JSONField(default=content.models.default_marquee_items)),
                ('features_eyebrow', models.CharField(default='Notre Philosophie', max_length=200)),
                ('features_title_plain', models.CharField(default='Pourquoi', max_length=200)),
                ('features_title_emphasis', models.CharField(default='Afro Cure ?', max_length=200)),
                ('features_description', models.TextField(default='Une gamme développée pour répondre aux besoins majeurs des cheveux texturés.')),
                ('feature_cards', models.JSONField(default=content.models.default_feature_cards)),
                ('products_eyebrow', models.CharField(default='Sélection', max_length=200)),
                ('products_title_plain', models.CharField(default='Produits', max_length=200)),
                ('products_title_emphasis', models.CharField(default='Vedettes', max_length=200)),
                ('products_description', models.TextField(default='Découvrez nos soins les plus populaires, plébiscités par notre communauté.')),
                ('products_footer_label', models.CharField(default='Voir tous les produits', max_length=100)),
                ('cta_eyebrow', models.CharField(default='Routine Personnalisée', max_length=200)),
                ('cta_title_plain', models.CharField(default='Révélez la beauté', max_length=200)),
                ('cta_title_emphasis', models.CharField(default='de vos cheveux', max_length=200)),
                ('cta_body', models.TextField(default='Une routine personnalisée pour des résultats visibles et durables. Chaque formule est pensée pour célébrer la beauté naturelle des cheveux texturés.')),
                ('cta_button_label', models.CharField(default='En savoir plus', max_length=100)),
                ('cta_pills', models.JSONField(default=content.models.default_cta_pills)),
                ('cta_image', models.ImageField(blank=True, null=True, upload_to='content/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
