# Generated by Django 6.0.3 on 2026-09-14 08:57

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Notre Histoire', max_length=200)),
                ('title_plain', models.CharField(default='Afro', max_length=200)),
                ('title_emphasis', models.CharField(default='Cure', max_length=200)),
                ('body', models.TextField(default="Afro Cure est née d'une conviction simple : les cheveux texturés méritent des soins à la hauteur de leur beauté. Nous combinons la richesse des plantes africaines avec la rigueur de la science cosmétique pour créer des formules qui transforment véritablement vos cheveux.")),
                ('cards', models.JSONField(default=content.models.default_about_cards)),
                ('cta_label', models.CharField(default='Découvrir nos soins', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
