# Generated by Django 6.0.3 on 2026-09-14 09:12

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_aboutcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Afro Cure — Collection', max_length=200)),
                ('title_plain', models.CharField(default='Nos', max_length=200)),
                ('title_emphasis', models.CharField(default='Soins', max_length=200)),
                ('description', models.TextField(default='Chaque formule est pensée pour nourrir, définir et célébrer la beauté naturelle des cheveux texturés.')),
                ('marquee_items', models.JSONField(default=content.models.default_products_marquee)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
