# Generated by Django 6.0.3 on 2026-09-14 09:22

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_productspagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_description', models.TextField(default='Des soins efficaces, équilibrés et adaptés aux besoins réels des cheveux texturés. Science cosmétique et plantes africaines.')),
                ('social_eyebrow', models.CharField(default='Suivez-nous', max_length=200)),
                ('facebook_url', models.CharField(blank=True, default='#', max_length=300)),
                ('instagram_url', models.CharField(blank=True, default='#', max_length=300)),
                ('twitter_url', models.CharField(blank=True, default='#', max_length=300)),
                ('marquee_items', models.JSONField(default=content.models.default_footer_marquee)),
                ('soins_label', models.CharField(default='Nos Soins', max_length=200)),
                ('soins_items', models.JSONField(default=content.models.default_footer_soins_items)),
                ('contact_email', models.CharField(default='contact@afrocure.fr', max_length=200)),
                ('copyright_text', models.CharField(default='© 2026 Afro Cure. Tous droits réservés.', max_length=200)),
                ('tagline', models.CharField(default='Célébrer la beauté naturelle', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
