# Generated by Django 6.0.3 on 2026-09-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_footercontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='testimonials_description',
            field=models.TextField(default='Des retours authentiques de celles qui ont adopté nos soins au quotidien.'),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='testimonials_eyebrow',
            field=models.CharField(default='Témoignages', max_length=200),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='testimonials_form_label',
            field=models.CharField(default='Laisser un avis', max_length=200),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='testimonials_title_emphasis',
            field=models.CharField(default='nos clientes', max_length=200),
        ),
        migrations.AddField(
            model_name='homecontent',
            name='testimonials_title_plain',
            field=models.CharField(default='Ce que disent', max_length=200),
        ),
    ]
