# Generated by Django 6.0.3 on 2026-09-22 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='dial_code',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
